version: '3.7'
services:
  backend:
    build:
      target: dev
    command: docker/entrypoint.local.sh
    ports:
      - "3000:3000/tcp"
    volumes:
      - ./:/app
      - backend_bundle:/app/vendor/bundle
    env_file:
      - ./.env

  db:
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  backend_bundle:
  postgres:
