default: &default
  adapter: postgresql
  database: <%= ENV.fetch("DATABASE_NAME") %>
  encoding: utf-8
  host: <%= ENV.fetch("DATABASE_HOST") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test
  min_messages: error

production:
  <<: *default
