name: Build and test changes on pull requests

on:
  pull_request:
    branches:
      - master

env:
  COMPOSE_TEST_FILE_NAME: "docker-compose.test.yml"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.8
          bundler-cache: true

      - name: Build and test app
        run: |
          bundle install
          rubocop
